### ISSUE TITLE
Maximum line-length of 120 columns is too short

### ISSUE THREAD

**Issue by Zombiefruit** [wix/tslint-wix-react#1]
I think it's a reasonable limit for plain old Javascript, and even most Typescript, but with Typescript + React it's not unheard of to have function declarations like:

`    private onKeyDown: React.EventHandler<SyntheticEvent<HTMLInputElement>> = (event: React.KeyboardEvent<HTMLInputElement>): void => {`

which takes 136 columns. I ended up shortening the line anyways, by using the more generic `Element` type:

`private onKeyDown: React.EventHandler<SyntheticEvent<Element>> = (event: React.KeyboardEvent<Element>): void => {`

but the length is still 118 columns which is cutting it close. 

Thanks in advance for any input.

**Comment by Zombiefruit** [comment]
Realized I could just do: 

`private onKeyDown: React.EventHandler<React.KeyboardEvent<Element>> = (event): void => {`

As this is the only example of a declaration this long in my code, I'm closing this as perhaps it's not a relevant as I thought.

**Comment by tyv** [comment]
@Zombiefruit you have to use line breaks in this case I think
