### ISSUE TITLE
Add rule for linting .only calls in tests

### ISSUE THREAD

**Issue by Zombiefruit** [wix/tslint-wix-react#11]
`mocha-avoid-only` is exactly what we want to implement, as found in the[ tslint-microsoft-contrib ](https://github.com/Microsoft/tslint-microsoft-contrib)project.

Edit: [this](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/mochaAvoidOnlyRule.ts) is the implementation

**Comment by tyv** [comment]
would be nice to use only one rule separately, without extending ruleset. 
it is easy, just add `rulesDirectory` and use one rule from that

**Comment by Zombiefruit** [comment]
I'm handling this.

**Comment by tyv** [comment]
released 6.0.0
