### ISSUE TITLE
indent rules

### ISSUE THREAD

**Issue by Ta4i** [wix/tslint-wix-react#3]
We missing rule for indentation:
`"indent": [true, "spaces", x]`

It should be there. The only one question is how many spaces should it use. To solve it - vote for next comments of this issue.

**Comment by Ta4i** [comment]
2 spaces

**Comment by Ta4i** [comment]
4 spaces

**Comment by qballer** [comment]
I don't think a vote is the way to resolve this issue. On most cases this doesn't matter, but we have a code base which uses 4 spaces. Changing this is technically easy, but will rewrite the code base and destroy history. For that you need to start with `git filter-branch` magic. I vote against it.

**Comment by tyv** [comment]
by destroying history you mean `blame`? 
it is not so important as we are on early stages (and by the good is should be already done)

> but we have a code base which uses 4 spaces

current code base has different styles. mainly 4 spaces.

**Comment by wtfil** [comment]
Ideally it would be nice also include some strict intent rule like [`ter-intent`](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/terIndentRule.md)

`ter-intent` does not allow to put extra tabs in between `{}`

**Comment by AviVahl** [comment]
4 spaces for code.
2 spaces for json or css.

**Comment by wtfil** [comment]
@avi anyway tslint will not lint `.css` and `.json` files

**Comment by VKobeliatsky** [comment]
It is high time to merge this. The crowd has voted for 4 spaces. We merge today. Speak now or be silent forever.
