### ISSUE TITLE
 object-curly-spacing rule

### ISSUE THREAD

**Issue by wtfil** [wix/tslint-wix-react#4]
Currently we did not have this rule and you could find both styles
```tsx
import { for, bar } from 'forbar';
```

and

```tsx
import {for, bar} from 'forbar';
```

It would be nice to agree on one of them.

We could fix this with [object-curly-spacing](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/objectCurlySpacingRule.md)

Pls, vote for one of two following comments

**Comment by wtfil** [comment]
```
"object-curly-spacing": [
    true,
    "always"
]
```

```tsx
import { for, bar } from 'forbar';
```

**Comment by wtfil** [comment]
```
"object-curly-spacing": [
    true,
    "newer"
]
```

```tsx
import {for, bar} from 'forbar';
```

**Comment by idoros** [comment]
Does this have any effect on multi-line / block imports (in case you bring in a lot of them)?
I care less about the spacing, but wouldn't like to lose the ability to have import blocks:
```js
import {
    a.
    b.
    c.
    d
} from 'foobar';
```

**Comment by tyv** [comment]
if it is correct `eslint` fork, it shouldn't

**Comment by wtfil** [comment]
@idoros
both of options are not affect the multiline imports. The basic idea of this rule is to have or not to have space between `{` and next visible char

**Comment by AviVahl** [comment]
I personally find it a lot more readable with the space. Voted for the first one.

**Comment by wtfil** [comment]
for me it is not that big different, but I don't like mix of both styles

**Comment by VKobeliatsky** [comment]
Looks like the time is long due to make a decision. We merge today. Speak now or be silent forever.
